// Generated by CoffeeScript 1.8.0
(function() {
  var call, lift, promise, _ref;

  promise = require("when").promise;

  _ref = require("when/generator"), lift = _ref.lift, call = _ref.call;

  module.exports = {
    promise: promise,
    async: lift,
    call: call
  };

}).call(this);
